Basic swagger setup. Enumeration values gives null-pointer exception.
Pubcrawler/stout pull request #13
Opened 2017-03-18 20:45 UTC by johnolos

Currently yields null-point exception due to enums in User and CrawlParticipants.

An alternative might be to remove enum-values and define type Status and Gener to be chars.

We won't have the same 'safety', but if we introduce validation rules for user submitted data anyway, then we won't need it.

2017-05-27 09:41 UTC, hawkaa requested changes
Ser veldig bra ut! Men jeg tror du må legge inn database-endringene i en ny migrasjon, hvis ikke blir de aldri kjørt 👍

2017-05-27 09:41 UTC, hawkaa commented on src/main/resources/db/migration/V001__Initial_Tables.sql
> +ALTER TABLE users
Jeg lurer egentlig på om dette burde være en ny migrasjon?

2017-05-27 09:41 UTC, hawkaa commented on src/main/resources/db/migration/V001__Initial_Tables.sql
> +  ADD CONSTRAINT ck_gender CHECK (gender IN ('F', 'M', 'O'));
Har du sett på enums i Postgresql?

2017-05-27 09:41 UTC, hawkaa commented on src/main/scala/ScalatraBootstrap.scala
> +    context.mount(new SwaggerController, "/docs")
👍

2017-05-27 09:41 UTC, hawkaa commented on src/main/resources/db/migration/V001__Initial_Tables.sql
> +  ADD CONSTRAINT ck_gender CHECK (gender IN ('F', 'M', 'O'));
Eller var det det som gav nullpointer exception?

2017-05-27 09:41 UTC, hawkaa commented on src/main/scala/io/pubcrawler/stout/controllers/CrawlController.scala
> +  override protected def applicationDescription: String = "Stout Crawl API"
Awesome!

2017-05-27 09:41 UTC, hawkaa commented on src/main/scala/io/pubcrawler/stout/controllers/CrawlController.scala
> +  val getCrawl = apiOperation[Crawl]("getCrawl")
Awesome!

2017-05-31 12:32 UTC, johnolos commented on src/main/resources/db/migration/V001__Initial_Tables.sql
> +  ADD CONSTRAINT ck_gender CHECK (gender IN ('F', 'M', 'O'));
Vi pratet om det, men legger inn diskusjonen her for andre som er interesserte.

Postgres og Slick støtter begge enums, men ikke swagger i Scalatra. Derfor må vi ty til manuelle constraints direkte i databasen.

2017-05-31 15:23 UTC, johnolos commented
@hawkaa Denne er klar til ny QA.

2017-06-06 04:49 UTC, hawkaa approved these changes
👍

2017-07-07 08:59 UTC, merged